[package]
name = "openssl-auto-le"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true, features = ["openssl"] }
actix-files.workspace = true

acme-lib = "0.8"
anyhow = "1"
env_logger.workspace = true
log.workspace = true
openssl.workspace = true
reqwest = "0.11"
