[package]
name = "mysql"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
dotenv = "0.15"
mysql = "24"
serde = { version = "1", features = ["derive"] }
